In [30]:
#import libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [31]:
# import datasets
y = pd.read_csv("../data/raw/train_labels.csv")
X = pd.read_csv("../data/raw/train_values.csv")

In [32]:
#split the dataset into train and test
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [33]:
# encodings

X_train_obj = X_train.select_dtypes(include='object')

for i in X_train_obj.columns:
    print(i)
    print(X_train.loc[:, i].unique())

land_surface_condition
['n' 'o' 't']
foundation_type
['r' 'u' 'w' 'i' 'h']
roof_type
['n' 'q' 'x']
ground_floor_type
['f' 'v' 'x' 'z' 'm']
other_floor_type
['x' 'q' 's' 'j']
position
['s' 't' 'j' 'o']
plan_configuration
['q' 'd' 'u' 'a' 's' 'm' 'c' 'n' 'o' 'f']
legal_ownership_status
['v' 'w' 'r' 'a']

In [34]:
#Label Encoding all columns

le_lsc = LabelEncoder()  #instantiate the Label Encoder
X_train['land_surface_condition'] = le_lsc.fit_transform(X_train['land_surface_condition'])

le_ft = LabelEncoder()  #instantiate the Label Encoder
X_train['foundation_type'] = le_ft.fit_transform(X_train['foundation_type'])

le_rt = LabelEncoder()  #instantiate the Label Encoder
X_train['roof_type'] = le_rt.fit_transform(X_train['roof_type'])

le_gft = LabelEncoder()  #instantiate the Label Encoder
X_train['ground_floor_type'] = le_gft.fit_transform(X_train['ground_floor_type'])

le_oft = LabelEncoder()  #instantiate the Label Encoder
X_train['other_floor_type'] = le_oft.fit_transform(X_train['other_floor_type'])

le_pos = LabelEncoder()  #instantiate the Label Encoder
X_train['position'] = le_pos.fit_transform(X_train['position'])

le_pc = LabelEncoder()  #instantiate the Label Encoder
X_train['plan_configuration'] = le_pc.fit_transform(X_train['plan_configuration'])

le_los = LabelEncoder()  #instantiate the Label Encoder
X_train['legal_ownership_status'] = le_los.fit_transform(X_train['legal_ownership_status'])


X_train

#it's ideal to always instantiate new LabelEncoders for different columns

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
170377,739427,13,257,8352,3,25,2,5,0,2,...,0,0,0,0,0,0,0,0,0,0
184895,17201,6,1076,9202,3,40,10,8,1,2,...,0,0,1,0,0,0,0,0,0,0
26740,723805,7,838,10723,2,45,8,5,2,2,...,0,0,0,0,0,0,0,0,0,0
198210,891512,7,555,2763,2,30,7,4,2,2,...,0,0,0,0,0,0,0,0,0,0
254313,484350,17,682,1039,3,30,6,7,2,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259178,79888,13,909,1626,2,25,6,5,2,2,...,0,0,0,0,0,0,0,0,0,0
103694,442764,10,1397,8182,2,5,5,4,0,2,...,0,0,0,0,0,0,0,0,0,0
131932,17256,8,1073,5249,3,20,22,7,1,2,...,0,1,0,0,0,0,0,0,0,0
146867,496181,10,76,1841,3,10,11,7,2,2,...,0,0,0,0,0,0,0,0,0,0
121958,246461,7,746,10603,2,0,7,5,2,2,...,0,0,0,0,0,0,0,0,0,0

In [35]:
X_train.dtypes

building_id                               int64
geo_level_1_id                            int64
geo_level_2_id                            int64
geo_level_3_id                            int64
count_floors_pre_eq                       int64
age                                       int64
area_percentage                           int64
height_percentage                         int64
land_surface_condition                    int64
foundation_type                           int64
roof_type                                 int64
ground_floor_type                         int64
other_floor_type                          int64
position                                  int64
plan_configuration                        int64
has_superstructure_adobe_mud              int64
has_superstructure_mud_mortar_stone       int64
has_superstructure_stone_flag             int64
has_superstructure_cement_mortar_stone    int64
has_superstructure_mud_mortar_brick       int64
has_superstructure_cement_mortar_brick    int64
has_superstructure_timber                 int64
has_superstructure_bamboo                 int64
has_superstructure_rc_non_engineered      int64
has_superstructure_rc_engineered          int64
has_superstructure_other                  int64
legal_ownership_status                    int64
count_families                            int64
has_secondary_use                         int64
has_secondary_use_agriculture             int64
has_secondary_use_hotel                   int64
has_secondary_use_rental                  int64
has_secondary_use_institution             int64
has_secondary_use_school                  int64
has_secondary_use_industry                int64
has_secondary_use_health_post             int64
has_secondary_use_gov_office              int64
has_secondary_use_use_police              int64
has_secondary_use_other                   int64
dtype: object

In [36]:
#Encoding for test data set

X_test['land_surface_condition'] = le_lsc.transform(X_test['land_surface_condition'])
X_test['foundation_type'] = le_ft.transform(X_test['foundation_type'])
X_test['roof_type'] = le_rt.transform(X_test['roof_type'])
X_test['ground_floor_type'] = le_gft.transform(X_test['ground_floor_type'])
X_test['other_floor_type'] = le_oft.transform(X_test['other_floor_type'])
X_test['position'] = le_pos.transform(X_test['position'])
X_test['plan_configuration'] = le_pc.transform(X_test['plan_configuration'])
X_test['legal_ownership_status'] = le_los.transform(X_test['legal_ownership_status'])

X_test

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
111801,1023112,10,1224,11128,1,20,7,3,2,2,...,0,0,0,0,0,0,0,0,0,0
91817,64407,22,1101,12483,2,60,7,6,2,2,...,0,0,0,0,0,0,0,0,0,0
251661,967834,26,39,11440,2,50,6,5,2,2,...,0,0,0,0,0,0,0,0,0,0
205479,36669,8,1073,2743,3,50,7,6,1,2,...,0,0,0,0,0,0,0,0,0,0
22618,242842,6,706,7959,2,15,8,4,2,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209800,1009416,17,51,8163,3,5,9,7,2,2,...,0,1,0,0,0,0,0,0,0,0
45779,530277,20,922,1378,2,10,8,5,2,2,...,0,0,0,0,0,0,0,0,0,0
177645,216791,7,1233,5131,2,35,6,5,2,2,...,0,1,0,0,0,0,0,0,0,0
36857,767934,10,142,3523,2,15,5,5,0,2,...,0,0,0,0,0,0,0,0,0,0
97716,670319,13,373,3746,2,10,5,5,2,2,...,0,0,0,0,0,0,0,0,0,0